name: Get Version

on:
  push:
    branches:
      - "master"

jobs: 
  dockerise:
    runs-on: ubuntu-latest
    steps:
      #check out the code
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: master

      #Reading version
      - name: Reading version
        id: getversion
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'package.json'
          prop_path: 'version'
      - name: Shows Version
        run: echo ${{steps.getversion.outputs.prop}}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      #check out the code
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      # This is the a separate action that sets up buildx runner
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      
      # And make it available for the builds
      - name: Build and push
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          tags: "anshikag04/insiatest:${{steps.getversion.outputs.prop}}"
          cache-from: type=local,src=/tmp/.buildx-cache   
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      
      # Remove the outdated cache
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      #Clear the auth token stored in docker config    
      - name: Logout of docker
        run: |
          docker logout

 





